sudo: required

services:
    - docker

language: c

env:
    - PYTHON_VERSION=3.6 NUMPY_VERSION=1.13.3
    - PYTHON_VERSION=3.6 NUMPY_VERSION=1.12.1
    - PYTHON_VERSION=3.6 NUMPY_VERSION=1.11.3

script:
    - IMAGE_NAME="dmonroy/numpy:${PYTHON_VERSION}-${NUMPY_VERSION}"
    - docker build -t $IMAGE_NAME dockerfiles/${PYTHON_VERSION}/${NUMPY_VERSION}

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE_NAME;
    fi
